#!/usr/bin/env bash
# scenarios/01_onboarding/run.sh
# Provisions workload-specific Vault resources and registers apps in Arcanium.
# Writes credentials to .env.workloads (gitignored).

set -euo pipefail

REPO_ROOT=$(cd "$(dirname "$0")/../.." && pwd)
ARCANIUM_API="${ARCANIUM_API:-http://localhost:3001}"

echo "[onboarding] starting"

# ── 1. Register applications in Arcanium API ─────────────────────────────
register_app() {
  local name="$1" desc="$2"
  # Check if already registered
  local existing
  existing=$(curl -sf "${ARCANIUM_API}/api/v1/applications" |
    jq -r --arg n "$name" '.[] | select(.name==$n) | .id' 2>/dev/null || true)
  if [ -n "$existing" ]; then
    echo "[onboarding] '$name' already registered: $existing"
    echo "$existing"
    return
  fi
  local id
  id=$(curl -sf -X POST "${ARCANIUM_API}/api/v1/applications" \
    -H "Content-Type: application/json" \
    -d "{\"name\":\"${name}\",\"description\":\"${desc}\"}" | jq -r .id)
  echo "[onboarding] registered '${name}': ${id}"
  echo "$id"
}

register_app "payments-api" "Transit encryption demo" >/dev/null
register_app "pki-client" "PKI certificate demo" >/dev/null

# ── 2. Apply workloads Terraform (creates key, roles, policies) ───────────
echo "[onboarding] applying vault-workloads terraform..."
make -C "$REPO_ROOT" tf-workloads

# ── 3. Generate AppRole secret_ids ────────────────────────────────────────
export VAULT_ADDR="${VAULT_ADDR:-https://127.0.0.1:18200}"
export VAULT_CACERT="${VAULT_CACERT:-${REPO_ROOT}/vault-tls/ca-chain.pem}"
export VAULT_TOKEN
VAULT_TOKEN=$(jq -r .root_token "${REPO_ROOT}/.secrets/vault/cluster-init.json")

echo "[onboarding] generating AppRole credentials..."

PAYMENTS_ROLE_ID=$(vault read -field=role_id auth/approle/role/payments-workload/role-id)
PAYMENTS_SECRET_ID=$(vault write -f -field=secret_id auth/approle/role/payments-workload/secret-id)
PKI_ROLE_ID=$(vault read -field=role_id auth/approle/role/pki-workload/role-id)
PKI_SECRET_ID=$(vault write -f -field=secret_id auth/approle/role/pki-workload/secret-id)

# ── 4. Write .env.workloads (gitignored) ──────────────────────────────────
cat >"${REPO_ROOT}/.env.workloads" <<EOF
# Generated by scenarios/01_onboarding/run.sh — do not commit
PAYMENTS_VAULT_ROLE_ID=${PAYMENTS_ROLE_ID}
PAYMENTS_VAULT_SECRET_ID=${PAYMENTS_SECRET_ID}
PKI_VAULT_ROLE_ID=${PKI_ROLE_ID}
PKI_VAULT_SECRET_ID=${PKI_SECRET_ID}
EOF

echo "[onboarding] .env.workloads written to ${REPO_ROOT}/.env.workloads"
echo "[onboarding] done — run: make workloads-up"
